print(10+10)
print(10+20)
print(10+30)
print(10+40)
print(10+50)
print(10+60)
print(10+70)
print(10+80)
print(10+90)
print(10+100)

print(20-10)
print(30-20)
print(50-10)
print(60-50)
print(70-60)
print(90-20)
print(100-50)
print(30-20)
print(40-20)
print(20-10)

print(50*10)
print(80*9)
print(70*65)
print(50*70)
print(40*2)
print(10*4)
print(90*70)
print(30*4)
print(40*90)
print(10*100)
 



2  # print ბრძანება გამოიყენე 40 ჯერ  გამოიყენეთ და დაბეჭდეთ თქვენთვის სასურველი ინფორმაცია

print("i am data")
print("my surname is gogilashvili")
print("my country is a georgia")
print(" live in nazaladevi")
print("on khudadov street")
print("I live in the tbilisi")
print("I studying 36 public at school")
print("my family is a large")
print("I am football player")
print(" jibo nizharadze teachers me football")
print("i am programer")
print("I am a programming, my squad teacher is giga")
print("I like playing bal in the yard")
print("I am chess player")
print("my teacer in chess is a davit gurgenidze")
print("I am studying programming in Goa")
print("I studying football in norchi dinamo")
print("I studying chess in National palace")
print("I know swiming in the pool")
print("I also went swimming")
print("I am beginner in programing")
print("I have been playng football for 4 years")
